### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by qingfeng55555** [dwHou/dwHou.github.io#1]
你好  我是电子科技大学的一名在读学生，看到您的一篇关于视频处理的论文《Super-Resolving Compressed Video in Coding Chain》,对此很感兴趣，想问问能否分享一下代码学习学习，如果有打扰到您，深感抱歉！

**Comment by dwHou** [comment]
没问题，已经把仓库开放给你了

**Comment by qingfeng55555** [comment]
For our simulation framework, the HEVC base layer was
encoded by software HM 16.0 while the HEVC enhance-
ment layer was encoded by SHM 6.1, and Bidirectionally
predicted frames (B-frames) are disabled in codec.



请问一下这里面的SHM6.1是什么编码器？能否给个链接了解一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dwHou/dwHou.github.io"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月30日(星期一) 下午4:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dwHou/dwHou.github.io] 求助 (Issue #1)





 
没问题，已经把仓库开放给你了

**Comment by dwHou** [comment]
[About SHVC and SHM](https://zhuanlan.zhihu.com/p/39438463 )
